// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
//
// NOTA: os imports usam os nomes mapeados no importmap (controllers/xxx) em vez
// de paths relativos (./xxx). Com o Propshaft os assets são fingerprinted, então
// imports relativos "./xxx" tentam buscar /assets/controllers/xxx.js sem digest,
// resultando em 404 e quebrando todo o bootstrap do Stimulus.

import { application } from "controllers/application"

import AuthModalController from "controllers/auth_modal_controller"
application.register("auth-modal", AuthModalController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import PricingController from "controllers/pricing_controller"
application.register("pricing", PricingController)

import RentalPricingController from "controllers/rental_pricing_controller"
application.register("rental-pricing", RentalPricingController)

import ThemeController from "controllers/theme_controller"
application.register("theme", ThemeController)