// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import AuthModalController from "controllers/auth_modal_controller"
application.register("auth-modal", AuthModalController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import PricingController from "controllers/pricing_controller"
application.register("pricing", PricingController)
