require:
  - standard

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'mobile/node_modules/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'config/initializers/*.rb'
    - 'spec/**/*'

Naming/PredicatePrefix:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'config/routes.rb'



